version: 2.1

parameters:
  ssh-fingerprint:
    type: string
    default: ${GITHUB_SSH_FINGERPRINT}

aliases:
  # Workflow filters
  - &filter-only-master
    branches:
      only: master
  - &filter-only-release
    branches:
      only: /^v[1-9]*[0-9]+\.[1-9]*[0-9]+\.x$/

workflows:
  plugin_workflow:
    jobs:
      - build
      - report:
          requires:
            - build
      - approve_release:
          type: approval
          requires:
            - report
          filters: *filter-only-release
      - publish_github_release:
          requires:
            - approve_release
          filters: *filter-only-release

executors:
  default_exec: # declares a reusable executor
    docker:
      - image: grafana/grafana-plugin-ci:1.5.1-alpine
  e2e_exec:
    docker:
      - image: grafana/grafana-plugin-ci-e2e:1.4.1

jobs:
  build:
    executor: default_exec
    steps:
      - checkout
      - restore_cache:
          name: restore node_modules
          keys:
          - build-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            mkdir ci
            [ -f ~/project/node_modules/.bin/grafana-toolkit ] || yarn install --frozen-lockfile
      - save_cache:
          name: save node_modules
          paths:
            - ~/project/node_modules
          key: build-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - save_cache:
          name: save cypress cache
          paths:
            - ~/.cache/Cypress
          key: cypress-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - run:
          name: Build and test panel 
          command: ~/project/node_modules/.bin/grafana-toolkit plugin:ci-build
      - run:
          name: Move results to ci folder
          command: ~/project/node_modules/.bin/grafana-toolkit plugin:ci-build --finish
      - run:
          name: Package distribution
          command: |
            ~/project/node_modules/.bin/grafana-toolkit plugin:ci-package
      - persist_to_workspace:
          root: .
          paths:
          - ci/jobs/package
          - ci/packages
          - ci/dist
          - ci/grafana-test-env
      - store_artifacts:
          path: ci

  report:
    executor: default_exec
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          name: restore node_modules
          keys:
            - build-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - run:
          name: Toolkit report
          command: |
            ~/project/node_modules/.bin/grafana-toolkit plugin:ci-report
      - store_artifacts:
          path: ci

  publish_github_release:
    executor: default_exec
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "${GITHUB_SSH_FINGERPRINT}"
      - attach_workspace:
          at: .
      - restore_cache:
          name: restore node_modules
          keys:
          - build-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - run:
          name: "Publish Release on GitHub"
          command: |
            ~/project/node_modules/.bin/grafana-toolkit plugin:github-publish
